/**
 * CustomerService — customer CRUD + sync event emission.
 *
 * Emits:
 *   - customer.created  — on createCustomer()
 *   - customer.updated   — on updateCustomer()
 *   - customer.archived — on archiveCustomer() (soft-delete: status → 'inactive')
 *   - customer.sale_assigned — on assignSaleToCustomer()
 *
 * Critical invariants:
 *   1. Customer must NEVER be duplicated by replay — idempotency by idempotency key.
 *   2. Sale referencing a customer must remain valid regardless of sync ordering
 *      (entity dependency ordering: customer creation and sale assignment are
 *      independent events that can arrive in any order).
 *   3. Business isolation enforced at service layer (this.businessId).
 */

import type { Customer, SyncEvent, SyncEngine } from '@soostori/contracts'
import type {
  BusinessId, CustomerId, SaleId, EmployeeId, DeviceId,
  IdempotencyKey, Money,
} from '@soostori/core'
import {
  newId,
  asCustomerId,
  asSyncEventId,
  asIdempotencyKey,
} from '@soostori/core'
import type { CustomerRepository, CustomerSearchFilter } from './repository.js'

// ── Input types ────────────────────────────────────────────────────────────────

export interface CreateCustomerInput {
  businessId: BusinessId
  name: string
  phone?: string | null
  email?: string | null
  idNumber?: string | null
  address?: string | null
  notes?: string | null
  /**
   * Idempotency key — UUID per create request.
   * Prevents duplicate submission on offline replay (§17, §6).
   * Caller (POS) generates this and passes it in.
   */
  idempotencyKey: IdempotencyKey
}

export interface UpdateCustomerInput {
  name?: string
  phone?: string | null
  email?: string | null
  idNumber?: string | null
  address?: string | null
  notes?: string | null
}

// ── Service ───────────────────────────────────────────────────────────────────

export class CustomerService {
  constructor(
    private readonly store: CustomerRepository,
    private readonly syncEngine: SyncEngine,
    private readonly businessId: BusinessId,
    private readonly deviceId: DeviceId,
    private readonly employeeId: EmployeeId,
  ) {}

  // ── create ──────────────────────────────────────────────────────────────────

  /**
   * Create a new customer.
   *
   * Idempotent: if a customer with the same idempotencyKey already exists,
   * returns that customer without creating a duplicate.
   *
   * The idempotency key is generated by the calling POS on the device.
   * Replay from any device with the same key returns the existing record.
   */
  async createCustomer(input: CreateCustomerInput): Promise<Customer> {
    if (input.businessId !== this.businessId) throw new Error('Business isolation violation')

    // Critical: idempotency check BEFORE any write.
    // This is the anti-duplication gate — replay must NEVER create a second row.
    const existing = await this.store.getCustomerByIdempotencyKey(input.idempotencyKey)
    if (existing) return existing

    const now = new Date().toISOString()
    const id = asCustomerId(newId())

    const customer: Customer = {
      id,
      businessId: this.businessId,
      name: input.name,
      phone: input.phone ?? null,
      email: input.email ?? null,
      idNumber: input.idNumber ?? null,
      address: input.address ?? null,
      notes: input.notes ?? null,
      balance: 0 as Money,
      status: 'active',
      createdAt: now,
      updatedAt: now,
      version: 1,
    }

    await this.store.upsertCustomer(customer)
    await this.emit('customer.created', customer, 'create')

    return customer
  }

  // ── update ───────────────────────────────────────────────────────────────────

  /**
   * Update mutable fields on an existing customer.
   * Last-writer-wins by version: incoming version <= stored version → no-op.
   */
  async updateCustomer(id: CustomerId, changes: UpdateCustomerInput): Promise<Customer> {
    const existing = await this.store.getCustomer(id)
    if (!existing) throw new Error(`Customer ${id} not found`)
    if (existing.businessId !== this.businessId) throw new Error('Business isolation violation')
    if (existing.status === 'inactive') throw new Error('Cannot update an archived customer')

    const now = new Date().toISOString()
    const updated: Customer = {
      ...existing,
      name: (changes.name !== undefined ? changes.name : existing.name) as Customer['name'],
      phone: changes.phone !== undefined ? changes.phone : existing.phone,
      email: changes.email !== undefined ? changes.email : existing.email,
      idNumber: changes.idNumber !== undefined ? changes.idNumber : existing.idNumber,
      address: changes.address !== undefined ? changes.address : existing.address,
      notes: changes.notes !== undefined ? changes.notes : existing.notes,
      updatedAt: now,
      version: existing.version + 1,
    }

    await this.store.upsertCustomer(updated)
    await this.emit('customer.updated', updated, 'update')

    return updated
  }

  // ── archive ─────────────────────────────────────────────────────────────────

  /**
   * Archive a customer (soft-delete).
   *
   * Sets status to 'inactive'. Archived customers are retained for historical
   * sale/debt records but excluded from active customer lists.
   *
   * Idempotent: if already inactive, returns without error.
   */
  async archiveCustomer(id: CustomerId): Promise<Customer> {
    const existing = await this.store.getCustomer(id)
    if (!existing) throw new Error(`Customer ${id} not found`)
    if (existing.businessId !== this.businessId) throw new Error('Business isolation violation')

    if (existing.status === 'inactive') return existing  // already archived — idempotent

    const now = new Date().toISOString()
    const archived: Customer = {
      ...existing,
      status: 'inactive',
      updatedAt: now,
      version: existing.version + 1,
    }

    await this.store.upsertCustomer(archived)
    await this.emit('customer.archived', archived, 'update')

    return archived
  }

  // ── lookup ──────────────────────────────────────────────────────────────────

  async getCustomer(id: CustomerId): Promise<Customer | null> {
    const customer = await this.store.getCustomer(id)
    if (!customer) return null
    if (customer.businessId !== this.businessId) return null  // hide non-owned
    return customer
  }

  /**
   * Fast phone lookup — used by POS quick-customer-search.
   * Returns null if no customer has this phone number in this business.
   */
  async getCustomerByPhone(phone: string): Promise<Customer | null> {
    return this.store.getCustomerByPhone(this.businessId, phone)
  }

  // ── list / search ───────────────────────────────────────────────────────────

  async listCustomers(filter: {
    status?: Customer['status'] | 'all'
    query?: string
    limit?: number
    offset?: number
  }): Promise<Customer[]> {
    return this.store.listCustomers({
      businessId: this.businessId,
      status: filter.status ?? 'all',
      query: filter.query,
      limit: filter.limit,
      offset: filter.offset,
    })
  }

  async countCustomers(filter: {
    status?: Customer['status'] | 'all'
    query?: string
  }): Promise<number> {
    return this.store.countCustomers({
      businessId: this.businessId,
      status: filter.status ?? 'all',
      query: filter.query,
    })
  }

  // ── sale / customer association ────────────────────────────────────────────

  /**
   * Assign a sale to a customer (e.g., attach walk-in customer to a sale post-checkout).
   *
   * Sale association is decoupled from customer creation — a sale can be assigned
   * to a customer that has not yet been synced to this device, because:
   *   - The customer entity and the sale entity are independent sync events.
   *   - `sale.customerId` is a reference, not a foreign-key constraint.
   *   - On replay, the sale can reference a customerId that hasn't arrived yet;
   *     the association is resolved when both events are processed.
   *
   * This method updates the sale record locally and emits a `customer.sale_assigned`
   * event so other devices can sync the link.
   *
   * @param saleId        The sale to assign — must have a `customerId` field
   *                      in the store's sale representation.
   * @param customerId     The customer to associate. Must exist in this business.
   *
   * NOTE: The actual sale update is delegated to a SaleRepository passed at
   * construction. CustomerService does NOT import SaleService to avoid a
   * circular dependency (inventory ↔ customers). Callers compose both services.
   */
  async assignSaleToCustomer(
    saleId: SaleId,
    customerId: CustomerId,
    saleRepo: { updateSaleCustomerId(saleId: SaleId, customerId: CustomerId): Promise<void> },
  ): Promise<void> {
    const customer = await this.store.getCustomer(customerId)
    if (!customer) throw new Error(`Customer ${customerId} not found`)
    if (customer.businessId !== this.businessId) throw new Error('Business isolation violation')

    await saleRepo.updateSaleCustomerId(saleId, customerId)

    const now = new Date().toISOString()
    const event: SyncEvent = {
      id: asSyncEventId(newId()),
      idempotencyKey: asIdempotencyKey(`${saleId}:${customerId}`),
      businessId: this.businessId,
      entityKind: 'customer',
      entityId: customerId,
      operation: 'update',
      originatingDeviceId: this.deviceId,
      originatingEmployeeId: this.employeeId,
      clientSequence: Date.now(),
      clientCreatedAt: now,
      entityVersion: customer.version,
      payload: { saleId, customerId, assignedAt: now } as Record<string, unknown>,
      state: 'pending',
    }
    await this.syncEngine.enqueue(event)
  }

  // ── emit ────────────────────────────────────────────────────────────────────

  private async emit(
    eventType: 'customer.created' | 'customer.updated' | 'customer.archived',
    entity: Customer,
    syncOp: SyncEvent['operation'],
  ): Promise<void> {
    // The idempotency key on the event is the entity's own idempotency key
    // (for customer.created) or a deterministic composite (for updates).
    const eventKey = eventType === 'customer.created'
      ? (entity as any).idempotencyKey ?? asIdempotencyKey(newId())
      : asIdempotencyKey(`${entity.id}:${eventType}`)

    const event: SyncEvent = {
      id: asSyncEventId(newId()),
      idempotencyKey: eventKey as IdempotencyKey,
      businessId: this.businessId,
      entityKind: 'customer',
      entityId: entity.id,
      operation: syncOp,
      originatingDeviceId: this.deviceId,
      originatingEmployeeId: this.employeeId,
      clientSequence: Date.now(),
      clientCreatedAt: new Date().toISOString(),
      entityVersion: entity.version,
      payload: entity as unknown as Record<string, unknown>,
      state: 'pending',
    }
    await this.syncEngine.enqueue(event)
  }
}
