/**
 * Validation schemas — zod-based, shared across all apps.
 */
import { z } from 'zod';
export declare const uuidSchema: z.ZodString;
export declare const iso8601Schema: z.ZodUnion<[z.ZodString, z.ZodString]>;
export declare const emailSchema: z.ZodString;
export declare const moneySchema: z.ZodNumber;
export declare const pinSchema: z.ZodString;
export declare const magicCodeSchema: z.ZodString;
export declare const inviteCodeSchema: z.ZodString;
export declare const shopSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    taxRate: z.ZodDefault<z.ZodNumber>;
    plan: z.ZodDefault<z.ZodString>;
    subscriptionExpiry: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodString]>>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "suspended"]>>;
}, "strict", z.ZodTypeAny, {
    status: "active" | "inactive" | "suspended";
    id: string;
    name: string;
    slug: string;
    taxRate: number;
    plan: string;
    subscriptionExpiry?: string | null | undefined;
}, {
    id: string;
    name: string;
    slug: string;
    status?: "active" | "inactive" | "suspended" | undefined;
    taxRate?: number | undefined;
    plan?: string | undefined;
    subscriptionExpiry?: string | null | undefined;
}>;
export declare const employeeRoleSchema: z.ZodEnum<["owner", "manager", "cashier", "attendant"]>;
export declare const employeeSchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    name: z.ZodString;
    email: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    phone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    role: z.ZodEnum<["owner", "manager", "cashier", "attendant"]>;
    permissions: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodBoolean>>>;
    cloudId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive"]>>;
}, "strict", z.ZodTypeAny, {
    status: "active" | "inactive";
    id: string;
    name: string;
    shopId: string;
    role: "owner" | "manager" | "attendant" | "cashier";
    email?: string | null | undefined;
    phone?: string | null | undefined;
    permissions?: Record<string, boolean> | null | undefined;
    cloudId?: string | null | undefined;
}, {
    id: string;
    name: string;
    shopId: string;
    role: "owner" | "manager" | "attendant" | "cashier";
    status?: "active" | "inactive" | undefined;
    email?: string | null | undefined;
    phone?: string | null | undefined;
    permissions?: Record<string, boolean> | null | undefined;
    cloudId?: string | null | undefined;
}>;
export declare const deviceSchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    deviceName: z.ZodString;
    deviceType: z.ZodEnum<["desktop", "mobile"]>;
    status: z.ZodDefault<z.ZodEnum<["pending", "authorized", "revoked", "offline"]>>;
    isLanHost: z.ZodDefault<z.ZodBoolean>;
    authorizedAt: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodString]>>>;
    lastSeenAt: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodString]>>>;
    lastSyncAt: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodString]>>>;
    tokenRef: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strict", z.ZodTypeAny, {
    status: "pending" | "revoked" | "authorized" | "offline";
    id: string;
    shopId: string;
    deviceName: string;
    deviceType: "desktop" | "mobile";
    isLanHost: boolean;
    authorizedAt?: string | null | undefined;
    lastSeenAt?: string | null | undefined;
    lastSyncAt?: string | null | undefined;
    tokenRef?: string | null | undefined;
}, {
    id: string;
    shopId: string;
    deviceName: string;
    deviceType: "desktop" | "mobile";
    status?: "pending" | "revoked" | "authorized" | "offline" | undefined;
    isLanHost?: boolean | undefined;
    authorizedAt?: string | null | undefined;
    lastSeenAt?: string | null | undefined;
    lastSyncAt?: string | null | undefined;
    tokenRef?: string | null | undefined;
}>;
export declare const productSchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    name: z.ZodString;
    barcode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    sku: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    categoryId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    categoryName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    costPrice: z.ZodDefault<z.ZodNumber>;
    sellingPrice: z.ZodNumber;
    groupPrices: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isGroup: z.ZodDefault<z.ZodBoolean>;
    unitsPerPackage: z.ZodDefault<z.ZodNumber>;
    stockQuantity: z.ZodDefault<z.ZodNumber>;
    currentStock: z.ZodDefault<z.ZodNumber>;
    lowStockThreshold: z.ZodDefault<z.ZodNumber>;
    trackInventory: z.ZodDefault<z.ZodBoolean>;
    allowSingleUnitSale: z.ZodDefault<z.ZodBoolean>;
    distributorName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    distributorPhone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodUnion<[z.ZodString, z.ZodString]>;
    updatedAt: z.ZodUnion<[z.ZodString, z.ZodString]>;
}, "strict", z.ZodTypeAny, {
    id: string;
    name: string;
    shopId: string;
    costPrice: number;
    sellingPrice: number;
    isGroup: boolean;
    unitsPerPackage: number;
    stockQuantity: number;
    currentStock: number;
    lowStockThreshold: number;
    trackInventory: boolean;
    allowSingleUnitSale: boolean;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    barcode?: string | null | undefined;
    sku?: string | null | undefined;
    categoryId?: string | null | undefined;
    categoryName?: string | null | undefined;
    groupPrices?: string | null | undefined;
    distributorName?: string | null | undefined;
    distributorPhone?: string | null | undefined;
    image?: string | null | undefined;
}, {
    id: string;
    name: string;
    shopId: string;
    sellingPrice: number;
    createdAt: string;
    updatedAt: string;
    barcode?: string | null | undefined;
    sku?: string | null | undefined;
    categoryId?: string | null | undefined;
    categoryName?: string | null | undefined;
    costPrice?: number | undefined;
    groupPrices?: string | null | undefined;
    isGroup?: boolean | undefined;
    unitsPerPackage?: number | undefined;
    stockQuantity?: number | undefined;
    currentStock?: number | undefined;
    lowStockThreshold?: number | undefined;
    trackInventory?: boolean | undefined;
    allowSingleUnitSale?: boolean | undefined;
    distributorName?: string | null | undefined;
    distributorPhone?: string | null | undefined;
    image?: string | null | undefined;
    isActive?: boolean | undefined;
}>;
export declare const categorySchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    name: z.ZodString;
    color: z.ZodDefault<z.ZodString>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodUnion<[z.ZodString, z.ZodString]>;
    updatedAt: z.ZodUnion<[z.ZodString, z.ZodString]>;
}, "strict", z.ZodTypeAny, {
    id: string;
    name: string;
    shopId: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    color: string;
    description?: string | null | undefined;
}, {
    id: string;
    name: string;
    shopId: string;
    createdAt: string;
    updatedAt: string;
    isActive?: boolean | undefined;
    color?: string | undefined;
    description?: string | null | undefined;
}>;
export declare const syncOperationSchema: z.ZodEnum<["create", "update", "delete"]>;
export declare const syncEventSchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    deviceId: z.ZodString;
    entity: z.ZodString;
    entityId: z.ZodString;
    operation: z.ZodEnum<["create", "update", "delete"]>;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    timestamp: z.ZodUnion<[z.ZodString, z.ZodString]>;
    version: z.ZodDefault<z.ZodNumber>;
    idempotencyKey: z.ZodString;
    syncedAt: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
}, "strict", z.ZodTypeAny, {
    id: string;
    shopId: string;
    deviceId: string;
    entity: string;
    entityId: string;
    operation: "create" | "update" | "delete";
    payload: Record<string, unknown>;
    timestamp: string;
    version: number;
    idempotencyKey: string;
    syncedAt?: string | undefined;
}, {
    id: string;
    shopId: string;
    deviceId: string;
    entity: string;
    entityId: string;
    operation: "create" | "update" | "delete";
    payload: Record<string, unknown>;
    timestamp: string;
    idempotencyKey: string;
    version?: number | undefined;
    syncedAt?: string | undefined;
}>;
export declare const planSchema: z.ZodObject<{
    id: z.ZodString;
    key: z.ZodString;
    name: z.ZodString;
    priceMonthly: z.ZodNumber;
    priceYearly: z.ZodNumber;
    deviceLimit: z.ZodNumber;
    features: z.ZodRecord<z.ZodString, z.ZodUnknown>;
}, "strict", z.ZodTypeAny, {
    id: string;
    name: string;
    key: string;
    priceMonthly: number;
    priceYearly: number;
    deviceLimit: number;
    features: Record<string, unknown>;
}, {
    id: string;
    name: string;
    key: string;
    priceMonthly: number;
    priceYearly: number;
    deviceLimit: number;
    features: Record<string, unknown>;
}>;
export declare const subscriptionSchema: z.ZodObject<{
    id: z.ZodString;
    shopId: z.ZodString;
    planId: z.ZodString;
    planKey: z.ZodString;
    status: z.ZodEnum<["active", "past_due", "expired", "cancelled", "trialing"]>;
    billingCycle: z.ZodEnum<["monthly", "yearly"]>;
    amountPaid: z.ZodDefault<z.ZodNumber>;
    currentPeriodStart: z.ZodUnion<[z.ZodString, z.ZodString]>;
    currentPeriodEnd: z.ZodUnion<[z.ZodString, z.ZodString]>;
    deviceLimit: z.ZodNumber;
}, "strict", z.ZodTypeAny, {
    status: "active" | "past_due" | "expired" | "cancelled" | "trialing";
    id: string;
    shopId: string;
    deviceLimit: number;
    planId: string;
    planKey: string;
    billingCycle: "monthly" | "yearly";
    amountPaid: number;
    currentPeriodStart: string;
    currentPeriodEnd: string;
}, {
    status: "active" | "past_due" | "expired" | "cancelled" | "trialing";
    id: string;
    shopId: string;
    deviceLimit: number;
    planId: string;
    planKey: string;
    billingCycle: "monthly" | "yearly";
    currentPeriodStart: string;
    currentPeriodEnd: string;
    amountPaid?: number | undefined;
}>;
//# sourceMappingURL=validation.d.ts.map